version: '3.3'

services:
  tinder-db:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pg123456'
      POSTGRES_DB: 'tinderDB'
    ports:
      - '5432:5432'
    volumes:
      - ../.data/pg96:/var/lib/postgresql/data/
    container_name: tinder-db
